### ISSUE TITLE
`dbx sync` ignores profile from `.dbx/project.json`

### ISSUE THREAD

**Issue by fjakobs** [databrickslabs/dbx#308]
## Expected Behavior

`dbx sync` should use the same profile resolution as the other dbx commands.

## Current Behavior

 Currently is ignores the profile in `.dbx/project.json`.

## Your Environment

* dbx version used:$ version ~> 0.6.3

**Comment by pietern** [comment]
You mean the Databricks profile in `~/.databrickscfg`, not `AWS_PROFILE`, I presume?

The profile is pulled from `DBX_CLI_PROFILE`.

See: https://github.com/databrickslabs/dbx/blob/2d09a50015a41078edce696b9b58d1c1bf17fb47/dbx/api/auth.py#L15-L28

**Comment by renardeinside** [comment]
resolved in linked PR

**Comment by gpadavala** [comment]
it still doesn't pick the "default" environment unless explicitly specified
`dbx sync --environment "default" -d <repo_name>`
but
`dbx sync -d <repo_name>` should also pick the default environment
